package sh.carr.ember.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GeneratePluginLoaderTask : DefaultTask() {
    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    abstract val kotlinStdlibVersion: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val cls = className.get()
        val version = kotlinStdlibVersion.get()
        val dir = outputDir.get().asFile.resolve(pkg.replace('.', '/'))
        dir.mkdirs()
        dir.resolve("$cls.java").writeText(
            """
            // Generated by :plugin:generatePluginLoader — do not edit.
            package $pkg;

            import io.papermc.paper.plugin.loader.PluginClasspathBuilder;
            import io.papermc.paper.plugin.loader.PluginLoader;
            import io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver;
            import org.eclipse.aether.artifact.DefaultArtifact;
            import org.eclipse.aether.graph.Dependency;
            import org.eclipse.aether.repository.RemoteRepository;

            @SuppressWarnings({"unused", "UnstableApiUsage"})
            public final class $cls implements PluginLoader {

                @Override
                public void classloader(final PluginClasspathBuilder classpathBuilder) {
                    var resolver = new MavenLibraryResolver();

                    resolver.addRepository(new RemoteRepository.Builder(
                            "central",
                            "default",
                            MavenLibraryResolver.MAVEN_CENTRAL_DEFAULT_MIRROR
                    ).build());

                    resolver.addDependency(new Dependency(
                            new DefaultArtifact("org.jetbrains.kotlin:kotlin-stdlib:$version"),
                            null
                    ));

                    classpathBuilder.addLibrary(resolver);
                }
            }
            """.trimIndent() + "\n",
        )
    }
}
