package sh.carr.ember.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GeneratePermissionConstantsTask : DefaultTask() {
    @get:Input
    abstract val permissionNames: ListProperty<String>

    @get:Input
    abstract val permissionDescriptions: MapProperty<String, String>

    @get:Input
    abstract val permissionDefaults: MapProperty<String, String>

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val commonPrefix: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        commonPrefix.convention("")
    }

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val prefix = commonPrefix.get()
        val descriptions = permissionDescriptions.get()
        val defaults = permissionDefaults.get()
        val dir = outputDir.get().asFile.resolve(pkg.replace('.', '/'))
        dir.mkdirs()

        val entries =
            permissionNames.get().sorted().joinToString("\n\n") { name ->
                val stripped = if (prefix.isNotEmpty() && name.startsWith(prefix)) name.removePrefix(prefix) else name
                val identifierSource = stripped.ifEmpty { name }
                val identifier = identifierSource.uppercase().replace(Regex("[^A-Z0-9]"), "_")
                val kdocLines =
                    buildList {
                        add("`$name`")
                        descriptions[name]?.let {
                            add("")
                            add(it)
                        }
                        defaults[name]?.let {
                            add("")
                            add("Default: `$it`.")
                        }
                    }
                val kdoc = kdocLines.joinToString("\n") { line -> "     * $line".trimEnd() }
                """
                |    /**
                |$kdoc
                |     */
                |    const val $identifier: String = "$name"
                """.trimMargin()
            }

        dir.resolve("Permissions.kt").writeText(
            buildString {
                appendLine("// Generated by :plugin:generatePermissionConstants — do not edit.")
                appendLine("package $pkg")
                appendLine()
                appendLine("internal object Permissions {")
                appendLine(entries)
                appendLine("}")
            },
        )
    }
}
