plugins {
    id("ember.common-conventions")
    `maven-publish`
}

base {
    archivesName = "ember-api"
}

val paperApiVersion: String by project

dependencies {
    compileOnly("io.papermc.paper:paper-api:$paperApiVersion")

    testImplementation("io.papermc.paper:paper-api:$paperApiVersion")
    testImplementation("org.mockbukkit.mockbukkit:mockbukkit-v26.1.2:4.113.1")
}

tasks {
    jacocoTestReport {
        classDirectories.setFrom(
            files(
                classDirectories.files.map {
                    fileTree(it) {
                        // Synthetic bridge class generated by kotlinc for interface default
                        // methods. Kotlin call sites use the real JVM default method instead, so
                        // the bridge is only reachable from legacy Java callers — none exist here.
                        exclude("**/*\$DefaultImpls.class")
                    }
                },
            ),
        )
    }
    jacocoTestCoverageVerification {
        classDirectories.setFrom(jacocoTestReport.get().classDirectories)
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            artifactId = "ember-api"
            pom {
                name = "ember-api"
                description = project.description
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/lukecarr/ember")
            credentials {
                username = providers.environmentVariable("GITHUB_ACTOR").getOrElse("")
                password = providers.environmentVariable("GITHUB_TOKEN").getOrElse("")
            }
        }
    }
}
